In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import random
import statistics
from mpl_toolkits import mplot3d
D=pd.read_csv("mmc4.csv")

In [2]:
import time
epoch=time.time()
t=time.ctime(epoch)

In [6]:
l=['File1.csv','File2.csv','File3.csv','File4.csv','File5.csv']
for i in range(5):   
    arr=np.random.randint(55,110,100000)
    dnew = pd.DataFrame(arr, columns=['heartbeat'])
    dnew.to_csv(l[i])
    print(dnew)

       heartbeat
0             71
1            108
2             88
3             78
4             60
...          ...
99995         75
99996         97
99997        104
99998         93
99999         90

[100000 rows x 1 columns]
       heartbeat
0             87
1             98
2            101
3             84
4             86
...          ...
99995         75
99996        102
99997        101
99998         89
99999         56

[100000 rows x 1 columns]
       heartbeat
0             68
1             95
2            106
3             84
4            106
...          ...
99995         82
99996         90
99997         56
99998         97
99999         70

[100000 rows x 1 columns]
       heartbeat
0             64
1             92
2             87
3             96
4             81
...          ...
99995        102
99996         70
99997         94
99998         74
99999         73

[100000 rows x 1 columns]
       heartbeat
0            103
1             81
2             67
3             91
4             70
...          ...
99995         82
99996         75
99997        107
99998         64
99999         98

[100000 rows x 1 columns]

In [7]:
for i in l:
    dnew=pd.read_csv(i)
    idx = pd.date_range(t, periods=100000, freq="1s")
    z=pd.DataFrame(idx)
    dnew["time_span"]=z
    dnew=dnew.drop('Unnamed: 0',axis=1)
    dnew=dnew.set_index(keys="time_span")
    dnew.to_csv(i)
    print(dnew)

                     heartbeat
time_span
2021-08-31 19:39:20         71
2021-08-31 19:39:21        108
2021-08-31 19:39:22         88
2021-08-31 19:39:23         78
2021-08-31 19:39:24         60
...                        ...
2021-09-01 23:25:55         75
2021-09-01 23:25:56         97
2021-09-01 23:25:57        104
2021-09-01 23:25:58         93
2021-09-01 23:25:59         90

[100000 rows x 1 columns]
                     heartbeat
time_span
2021-08-31 19:39:20         87
2021-08-31 19:39:21         98
2021-08-31 19:39:22        101
2021-08-31 19:39:23         84
2021-08-31 19:39:24         86
...                        ...
2021-09-01 23:25:55         75
2021-09-01 23:25:56        102
2021-09-01 23:25:57        101
2021-09-01 23:25:58         89
2021-09-01 23:25:59         56

[100000 rows x 1 columns]
                     heartbeat
time_span
2021-08-31 19:39:20         68
2021-08-31 19:39:21         95
2021-08-31 19:39:22        106
2021-08-31 19:39:23         84
2021-08-31 19:39:24        106
...                        ...
2021-09-01 23:25:55         82
2021-09-01 23:25:56         90
2021-09-01 23:25:57         56
2021-09-01 23:25:58         97
2021-09-01 23:25:59         70

[100000 rows x 1 columns]
                     heartbeat
time_span
2021-08-31 19:39:20         64
2021-08-31 19:39:21         92
2021-08-31 19:39:22         87
2021-08-31 19:39:23         96
2021-08-31 19:39:24         81
...                        ...
2021-09-01 23:25:55        102
2021-09-01 23:25:56         70
2021-09-01 23:25:57         94
2021-09-01 23:25:58         74
2021-09-01 23:25:59         73

[100000 rows x 1 columns]
                     heartbeat
time_span
2021-08-31 19:39:20        103
2021-08-31 19:39:21         81
2021-08-31 19:39:22         67
2021-08-31 19:39:23         91
2021-08-31 19:39:24         70
...                        ...
2021-09-01 23:25:55         82
2021-09-01 23:25:56         75
2021-09-01 23:25:57        107
2021-09-01 23:25:58         64
2021-09-01 23:25:59         98

[100000 rows x 1 columns]